import google.generativeai as genai
import os


def analyze_markdown_with_gemini(markdown_content):
    """
    Analyzes the provided Markdown content using Google Gemini.

    Args:
        markdown_content (str): The Markdown content to analyze.

    Returns:
        str: The analysis generated by Gemini, or None if an error occurs.
    """
    try:
        # Configure Gemini API (replace with your actual API key)
        genai.configure(api_key=os.environ.get("GOOGLE_API_KEY"))
        model = genai.GenerativeModel('gemini-1.5-flash')

        prompt = f"""
        
        You are tasked with performing a detailed financial analysis of a company based on the provided data. The data includes the following sections:

        Balance Sheet (from 12 Quarters)
        
        Profit & Loss (from 12 Years)
        
        Balance Sheet (from 12 Years)
        
        Cash Flows (from 12 Years)
        
        Shareholding Pattern (from 12 Years)
        
        Your goal is to extract insights, trends, and key observations from each section of the provided data without making any assumptions or introducing external data. Ensure your analysis is strictly based on the data provided, and break down the analysis for each section in detail. Provide a thorough interpretation of the financial health, performance, and changes over time.
        
        Here’s how you should approach the analysis:
        
        Balance Sheet (from 12 Quarters):
        
        Assess the company’s assets, liabilities, and equity over the 12-quarter period.
        
        Identify any significant changes, trends, or patterns, such as shifts in assets or liabilities, changes in liquidity, or shifts in equity.
        
        Calculate key financial ratios (e.g., current ratio, quick ratio, debt-to-equity ratio) and comment on the company’s short-term financial position and solvency.
        
        Profit & Loss (from 12 Years):
        
        Analyze the company’s revenue, expenses, and net income over the 12-year period.
        
        Identify any trends in growth or decline in revenues or costs, and assess profitability (gross margin, operating margin, and net margin).
        
        Provide insights into the company’s earnings stability, cost structure, and overall profit trajectory.
        
        Balance Sheet (from 12 Years):
        
        Examine the company’s balance sheet over the 12-year period.
        
        Focus on the long-term trends in assets, liabilities, and equity.
        
        Identify significant changes, such as asset accumulation or reduction, shifts in liabilities, or equity growth/decline.
        
        Highlight any major changes in the financial structure and provide insights into the company’s long-term financial health.
        
        Cash Flows (from 12 Years):
        
        Analyze the company’s cash flow from operating, investing, and financing activities over the 12 years.
        
        Comment on the overall cash flow trend, highlighting any significant surpluses or deficits in cash flow.
        
        Provide insights into the company’s ability to generate cash, manage investments, and finance its activities.
        
        Assess liquidity, solvency, and financial flexibility based on cash flow patterns.
        
        Shareholding Pattern (from 12 Years):
        
        Review the changes in the company’s shareholding pattern over the 12-year period.
        
        Identify any significant changes in ownership, such as increases or decreases in institutional, retail, or promoter holdings.
        
        Analyze how changes in the shareholding structure may reflect the company’s strategy, governance, or financial position.
        
        Instructions:
        
        For each section, provide insights, interpretations, and conclusions based strictly on the data.
        
        Avoid introducing any external data or making assumptions. Focus only on what is presented in the provided information.
        
        Each section should have a clear and structured analysis.
        
        Highlight any significant trends, anomalies, or important observations that could impact the company’s financial outlook.

        ---
        {markdown_content}
        ---

        Analysis:
        """

        response = model.generate_content(prompt)
        return response.text

    except Exception as e:
        print(f"Error during Gemini analysis: {e}")
        return None
